<a href="https://colab.research.google.com/github/aslyldrm/python-baseball-salary-prediction/blob/main/Baseball_Salary_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Baseball Salary Prediction**

# **Importing the libraries**

In [29]:
import numpy as np
import matplotlib.pyplot as pit
import pandas as pd

# Importing the dataset

In [30]:
dataset = pd.read_csv('hitters.csv')
X = dataset.iloc[:, :].values
y = dataset.loc[:, ['Salary']].values

In [31]:
X = np.delete(X, 18, axis=1)

In [50]:
dataset.shape

(322, 20)

In [32]:
print(X)

[[293 66 1 ... 33 20 'A']
 [315 81 7 ... 43 10 'N']
 [479 130 18 ... 82 14 'A']
 ...
 [475 126 3 ... 113 7 'A']
 [573 144 9 ... 131 12 'A']
 [631 170 9 ... 4 3 'A']]


# Taking care of missing data

In [33]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(y)
y = imputer.transform(y)



In [34]:
print(y)

[[ 535.92588213]
 [ 475.        ]
 [ 480.        ]
 [ 500.        ]
 [  91.5       ]
 [ 750.        ]
 [  70.        ]
 [ 100.        ]
 [  75.        ]
 [1100.        ]
 [ 517.143     ]
 [ 512.5       ]
 [ 550.        ]
 [ 700.        ]
 [ 240.        ]
 [ 535.92588213]
 [ 775.        ]
 [ 175.        ]
 [ 535.92588213]
 [ 135.        ]
 [ 100.        ]
 [ 115.        ]
 [ 535.92588213]
 [ 600.        ]
 [ 776.667     ]
 [ 765.        ]
 [ 708.333     ]
 [ 750.        ]
 [ 625.        ]
 [ 900.        ]
 [ 535.92588213]
 [ 110.        ]
 [ 535.92588213]
 [ 612.5       ]
 [ 300.        ]
 [ 850.        ]
 [ 535.92588213]
 [  90.        ]
 [ 535.92588213]
 [ 535.92588213]
 [  67.5       ]
 [ 535.92588213]
 [ 535.92588213]
 [ 180.        ]
 [ 535.92588213]
 [ 305.        ]
 [ 215.        ]
 [ 247.5       ]
 [ 535.92588213]
 [ 815.        ]
 [ 875.        ]
 [  70.        ]
 [ 535.92588213]
 [1200.        ]
 [ 675.        ]
 [ 415.        ]
 [ 340.        ]
 [ 535.92588213]
 [ 416.667    

# Encoding categorical data

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [-1,13,14])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

# Splitting the dataset into the Training set and Test set

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state=1)

In [52]:
print(X_train)

[[1.0 0.0 1.0 -0.9286112429750729 -0.9655727973942059 0.9655727973942061
  0.5484264612772287 0.25837135729489036 0.8814836837805534
  0.17841436883642678 0.26759567427633896 -0.10856467542713215
  -1.0826750395753244 -0.823315933199103 -0.8274861936455118
  -0.5181717445440702 -0.8234445411168952 -0.7577354581114254
  -0.774071768493445 -0.6183044373940553 0.8326138069808516
  0.4312849393622849]
 [0.0 1.0 0.0 1.0768769036181514 -0.9655727973942059 0.9655727973942061
  1.2390198882697425 1.2383091776157735 1.1146708240086565
  1.5465620650714298 1.0611197699188673 1.688456714778584
  1.579000683177552 2.3744877555065464 2.400342401779175
  1.4063612834352803 2.1194225466240386 2.118545585287866
  1.9075732854937437 -0.6393825317601514 1.2976019876552047
  0.27604652281311515]
 [1.0 0.0 1.0 -0.9286112429750729 1.035654693979269 -1.0356546939792692
  -0.5358697605427928 -0.7215664630259929 -1.1006070081583235
  -0.759744051439004 -0.6770758681552423 -1.101655443698712
  -1.2874193259409

# Feature Scaling

In [73]:
#For not dominating some features to others :

# -  Standardisation between 3 and -3  Always work
# - Normalization between 1 and -1  Works for which has normal distributions
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

X_train[:, 3:] = sc_X.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc_X.transform(X_test[:, 3:])

sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)
y_test = sc_y.transform(y_test)

In [55]:
X_train

array([[1.0, 0.0, 1.0, -0.9286112429750727, -0.9655727973942072,
        0.9655727973942074, 0.5484264612772288, 0.2583713572948903,
        0.8814836837805534, 0.1784143688364268, 0.26759567427633885,
        -0.10856467542713213, -1.0826750395753246, -0.823315933199103,
        -0.8274861936455119, -0.5181717445440703, -0.8234445411168952,
        -0.7577354581114252, -0.774071768493445, -0.6183044373940554,
        0.8326138069808519, 0.43128493936228485],
       [0.0, 1.0, 0.0, 1.076876903618152, -0.9655727973942072,
        0.9655727973942074, 1.2390198882697427, 1.2383091776157735,
        1.1146708240086565, 1.5465620650714302, 1.0611197699188668,
        1.6884567147785836, 1.5790006831775523, 2.3744877555065464,
        2.4003424017791755, 1.4063612834352806, 2.1194225466240386,
        2.1185455852878654, 1.9075732854937437, -0.6393825317601515,
        1.297601987655205, 0.2760465228131151],
       [1.0, 0.0, 1.0, -0.9286112429750727, 1.0356546939792703,
        -1.035654693

In [46]:
y_train

array([[-1.00522176],
       [ 0.66860647],
       [ 0.0433424 ],
       [ 0.0433424 ],
       [-0.11600051],
       [-0.75676289],
       [-0.50830401],
       [-1.09675925],
       [ 2.0416687 ],
       [-0.52138079],
       [-0.73060932],
       [ 0.0433424 ],
       [ 0.21091906],
       [ 0.93014213],
       [ 4.20543954],
       [ 2.06782226],
       [ 0.0433424 ],
       [ 1.25706171],
       [-0.50830401],
       [-1.16214316],
       [ 0.66860647],
       [ 0.99552605],
       [-0.9006075 ],
       [-0.31215226],
       [-0.67830219],
       [-0.63253345],
       [-1.09675925],
       [ 0.0433424 ],
       [ 0.0433424 ],
       [-0.83522358],
       [ 0.60322256],
       [-0.58022631],
       [ 0.60322256],
       [-0.35138261],
       [ 0.0433424 ],
       [-0.24676834],
       [-0.63907184],
       [-0.63253345],
       [-1.16214316],
       [ 0.01476732],
       [-0.44292009],
       [ 0.0433424 ],
       [ 5.07548238],
       [-0.57368792],
       [ 0.39399403],
       [ 2

# Multiple Linear Regression

In [58]:
from sklearn.linear_model import LinearRegression
regressor_lin_mul = LinearRegression()
regressor_lin_mul.fit(X_train, y_train)

LinearRegression()

In [59]:
y_pred_mul = regressor_lin_mul.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_mul.reshape(len(y_pred_mul),1), y_test.reshape(len(y_test),1)),1))

[[-0.34 -0.86]
 [-0.44 -0.18]
 [-0.46  0.04]
 [ 0.34  0.04]
 [-0.82  0.04]
 [-0.44  0.04]
 [ 0.98  1.13]
 [ 2.4   4.95]
 [ 1.07  3.68]
 [-0.5  -0.91]
 [-0.48 -0.98]
 [ 0.31  0.04]
 [-0.99 -1.07]
 [ 0.17 -0.77]
 [-0.61 -0.27]
 [ 1.28  2.17]
 [-0.12  0.04]
 [-0.15  0.04]
 [-0.49 -1.18]
 [-0.11  0.21]
 [-0.01 -0.31]
 [-0.49 -0.12]
 [-0.46 -0.72]
 [-0.58  0.04]
 [ 0.54 -0.4 ]
 [ 0.67  0.93]
 [-0.11  0.6 ]
 [ 0.5   0.04]
 [ 0.17 -1.04]
 [-0.61 -0.02]
 [ 1.42  0.04]
 [ 0.99  3.01]
 [-0.03 -0.18]
 [-0.3   0.2 ]
 [ 0.14  0.08]
 [ 0.85  0.47]
 [-0.72 -0.57]
 [-0.08  0.08]
 [-0.11  0.6 ]
 [-0.29 -0.99]
 [ 0.47  1.26]
 [ 0.05  1.  ]
 [ 0.5   2.04]
 [-0.24  0.04]
 [ 1.05  0.04]
 [-0.18 -0.5 ]
 [ 0.24  3.72]
 [-0.2  -0.57]
 [-0.8  -1.16]
 [-0.01 -0.31]
 [-0.51 -0.41]
 [-0.28 -0.23]
 [-0.81 -0.38]
 [ 0.29 -0.44]
 [-0.52 -0.94]
 [-0.37 -0.95]
 [ 1.34  0.56]
 [-0.04 -0.84]
 [ 0.22 -1.12]
 [-0.05  1.37]
 [ 0.15  0.47]
 [-0.54 -1.18]
 [ 2.07  3.35]
 [-0.71 -0.35]
 [ 0.17  1.52]]


In [89]:
from sklearn.metrics import r2_score
r2_score_multiple_lin = r2_score(y_test, y_pred_mul)

# Polynomial Regression

In [61]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

In [62]:
y_pred_poly = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_poly.reshape(len(y_pred_poly),1), y_test.reshape(len(y_test),1)),1))

[[-1.41e-01 -8.59e-01]
 [-4.97e-01 -1.81e-01]
 [-7.75e-01  4.33e-02]
 [ 1.37e-01  4.33e-02]
 [ 1.22e-01  4.33e-02]
 [-1.37e+00  4.33e-02]
 [ 6.26e-01  1.13e+00]
 [-8.28e-01  4.95e+00]
 [ 3.02e+00  3.68e+00]
 [-1.37e-01 -9.08e-01]
 [-7.38e-01 -9.79e-01]
 [-2.38e+00  4.33e-02]
 [-5.01e-01 -1.07e+00]
 [-2.59e-01 -7.70e-01]
 [-8.26e-01 -2.69e-01]
 [-3.11e+00  2.17e+00]
 [-4.73e-01  4.33e-02]
 [-3.13e-01  4.33e-02]
 [-3.77e-01 -1.18e+00]
 [-1.21e-01  2.11e-01]
 [-8.64e-01 -3.12e-01]
 [-2.91e-01 -1.16e-01]
 [-4.72e-01 -7.18e-01]
 [-2.51e+00  4.33e-02]
 [ 1.07e+01 -4.04e-01]
 [ 8.19e+00  9.30e-01]
 [ 4.24e-01  6.03e-01]
 [ 2.09e+00  4.33e-02]
 [-2.61e+00 -1.04e+00]
 [-8.17e-01 -1.79e-02]
 [-6.92e+00  4.33e-02]
 [-2.32e+00  3.01e+00]
 [ 1.40e+00 -1.81e-01]
 [-4.68e-01  1.98e-01]
 [-5.45e-02  8.02e-02]
 [-7.96e-01  4.72e-01]
 [-4.31e-01 -5.74e-01]
 [ 2.34e-01  8.02e-02]
 [ 1.44e-04  6.03e-01]
 [-8.69e-01 -9.92e-01]
 [ 1.72e+00  1.26e+00]
 [ 3.08e+00  9.96e-01]
 [-4.99e-01  2.04e+00]
 [-1.98e-01

In [88]:
from sklearn.metrics import r2_score
r2_score_poly_reg = r2_score(y_test, y_pred_poly)

# Linear Regression

In [64]:
from sklearn.linear_model import LinearRegression
regressor_linear = LinearRegression()
regressor_linear.fit(X_train,y_train)

LinearRegression()

In [65]:
y_pred_linear = regressor_linear.predict(X_test)

In [86]:
r2_score_reg_linear = r2_score(y_test, y_pred_poly)

# Random Forest Regressor

In [123]:
from sklearn.ensemble import RandomForestRegressor
regressor_rg = RandomForestRegressor(n_estimators = 25,min_samples_split = 5)
regressor_rg.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(min_samples_split=5, n_estimators=25)

In [121]:
y_pred_rg = regressor_rg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_rg.reshape(len(y_pred_rg),1), y_test.reshape(len(y_test),1)),1))

[[-0.38 -0.86]
 [-0.05 -0.18]
 [-0.6   0.04]
 [ 0.43  0.04]
 [-0.18  0.04]
 [-0.86  0.04]
 [ 2.1   1.13]
 [ 1.92  4.95]
 [ 1.55  3.68]
 [-0.72 -0.91]
 [-0.77 -0.98]
 [ 2.    0.04]
 [-0.92 -1.07]
 [-0.11 -0.77]
 [-0.32 -0.27]
 [ 1.11  2.17]
 [-0.56  0.04]
 [-0.45  0.04]
 [-0.9  -1.18]
 [ 0.31  0.21]
 [-0.28 -0.31]
 [-0.54 -0.12]
 [-0.24 -0.72]
 [ 0.49  0.04]
 [ 0.95 -0.4 ]
 [ 0.6   0.93]
 [ 0.7   0.6 ]
 [ 0.34  0.04]
 [-0.99 -1.04]
 [ 0.14 -0.02]
 [ 0.73  0.04]
 [ 1.56  3.01]
 [ 0.09 -0.18]
 [ 0.24  0.2 ]
 [ 0.25  0.08]
 [ 0.41  0.47]
 [-0.5  -0.57]
 [-0.2   0.08]
 [ 0.46  0.6 ]
 [-0.99 -0.99]
 [ 0.68  1.26]
 [ 1.18  1.  ]
 [ 1.45  2.04]
 [ 0.54  0.04]
 [ 2.6   0.04]
 [ 0.32 -0.5 ]
 [ 0.64  3.72]
 [-0.33 -0.57]
 [-0.87 -1.16]
 [-0.17 -0.31]
 [-0.07 -0.41]
 [-0.42 -0.23]
 [-0.34 -0.38]
 [ 0.04 -0.44]
 [-0.68 -0.94]
 [-0.85 -0.95]
 [ 0.42  0.56]
 [-0.64 -0.84]
 [-0.97 -1.12]
 [ 0.48  1.37]
 [ 0.73  0.47]
 [-0.93 -1.18]
 [ 1.62  3.35]
 [ 0.02 -0.35]
 [ 0.32  1.52]]


In [118]:
re2_score_rfg = r2_score(y_test, y_pred_rg)

# Support Vector Regression (SVR)

In [102]:
from sklearn.svm import SVR
regressor_svr = SVR(kernel = 'rbf')
regressor_svr.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [98]:
y_pred_svr = regressor_svr.predict(X_test)


In [99]:
r2_score_svr = r2_score(y_test, y_pred_svr)

# Results

In [122]:
print("Support Vector Regression: " + str(r2_score_svr))
print("Polynomial Regression: " + str(r2_score_poly_reg))
print("Linear Regression: " + str(r2_score_reg_linear))
print("Random Forest Regression: " + str(re2_score_rfg))
print("Multiple Linear regression: " + str(r2_score_multiple_lin))


Support Vector Regression: 0.4868177965416187
Polynomial Regression: -8.183588101669706
Linear Regression: -8.183588101669706
Random Forest Regression: 0.5156506574331081
Multiple Linear regression: 0.4534986198508628
